const translations = {
    'en': {
        'YesLabel': "Certainly, I'll be happy to come",
        'NoLabel': "Unfortunately, I won't be able to attend",
        'brideLabel': "Bride's",
        'groomLabel': "Groom's",
        'navbar__logo': 'INVITATION',
        'hero_header': 'Kamron & Malika',
        'hero_subheader': 'are inviting You to their wedding <br /> 21.12.2023',
        'invit_header': 'Dear Guests!',
        'invit_body': 'It is a great pleasure to invite You to share the joy of the special event for us - our wedding! <br /><br /> On this wonderful day, we would like to surround ourselves with your warmth and support and make this day unforgettable for all of us.',
        'invitation': 'We invite you!',
        'map': 'How to go there?',
        'plan': 'Plan of wedding',
        'time__left': 'Time left...',
        'calendar__weekday': 'Thursday',
        'calendar__weekmonth': 'December',
        'calendar__month': 'December 2023',
        'program__header': 'PROGRAM OF <br />THE DAY:',
        'program__photo': 'PHOTO-<br />SHOOTING',
        'program__event': 'MAIN EVENT',
        'program__cake': 'CAKE<br />CUTTING',
        'location__header': 'LOCATION',
        'location__subheader': 'RESTAURANT “GRAND HALL”',
        'location__location': 'Tashkent, Yunusabad district, Yunusabad massif, 13th quarter, 15A',
        'location__yandex': 'YANDEX MAPS...',
        'dress__header': 'DRESS CODE',
        'dress__subheader': 'We will be grateful <br /> if You support the wedding <br /> day color palette.',
        'dress__quest': 'QUESTIONNAIRE',
        'dress__body': 'YOUR PRESENCE IS INCREDIBLY <br /> IMPORTANT TO US, AND WE WILL <br /> BE HAPPY TO SHARE THIS <br /> MOMENT WITH YOU.',
        'form__header': 'Please answer a few questions that we have prepared for You.',
        'form__form-header': 'Whose side are you a guest from?',
        'bride': 'Bride’s',
        'groom': 'Groom’s',
        'form__form-header-attendance': 'Will you be able to attend our celebration?',
        'yes': 'Certainly, I will be happy to come',
        'no': 'Unfortunately, I will not be able to attend',
        'form__subheader': 'IF YOU WISH YOU CAN SHARE YOUR WISHES TO US HERE',
        'form__submit': 'SEND',
        'time__header': 'WE ARE WAITING <br /> FOR YOU IN...',
        'time__days': 'Days',
        'time__hours': 'Hours',
        'time__minutes': 'Minutes',
        'time__seconds': 'Seconds'
    },
    'ru': {
        'YesLabel': "Конечно, я с удовольствием приду.",
        'NoLabel': "К сожалению, я не смогу присутствовать.",
        'brideLabel': "Невесты",
        'groomLabel': "Жениха",
        'navbar__logo': 'ПРИГЛАШЕНИЕ',
        'hero_header': 'Камрон и Малика',
        'hero_subheader': 'приглашают вас на свою свадьбу <br /> 21.12.2023',
        'invit_header': 'Дорогие гости!',
        'invit_body': 'Мы очень рады пригласить Вас разделить радость особенного для нас события – нашей свадьбы! <br /><br /> В этот чудесный день нам хотелось бы окружить себя вашим теплом и поддержкой и сделать этот день незабываемым для всех нас.',
        'invitation': 'Мы приглашаем вас!',
        'map': 'Как туда попасть?',
        'plan': 'План свадьбы',
        'time__left': 'Осталось времени...',
        'calendar__weekday': 'Четверг',
        'calendar__weekmonth': 'Декабрь',
        'calendar__month': 'Декабрь 2023',
        'program__header': 'ПРОГРАММА <br />ДНЯ:',
        'program__photo': 'ФОТОСЕССИЯ',
        'program__event': 'ГЛАВНОЕ СОБЫТИЕ',
        'program__cake': 'НАРЕЗКА ТОРТА',
        'location__header': 'Расположение',
        'location__subheader': 'РЕСТОРАН "ГРАНД ХОЛЛ"',
        'location__location': 'Ташкент, Юнусабадский район, Юнусабадский массив, 13-й квартал, 15А',
        'location__yandex': 'Открыть на Яндекс Карты',
        'dress__header': 'Дресс-код',
        'dress__subheader': 'Будем признательны, если Вы поддержите цветовую палитру свадебного дня.',
        'dress__quest': 'Анкета',
        'dress__body': 'Ваше присутствие невероятно важно для нас, и мы будем рады разделить этот момент с Вами.',
        'form__header': 'Пожалуйста, ответьте на несколько вопросов, которые мы подготовили для Вас.',
        'form__form-header': 'С чьей стороны вы гость?*',
        'bride': 'Невесты',
        'groom': 'Жениха',
        'form__form-header-attendance': 'Сможете ли вы присутствовать на нашем торжестве?*',
        'yes': 'Конечно, я с удовольствием приду',
        'no': 'К сожалению, я не смогу присутствовать.',
        'form__subheader': 'Если хотите, Вы можете здесь оставить свои пожелания нам.',
        'form__submit': 'Отправить',
        'time__header': 'Мы ждем вас через...',
        'time__days': 'Дней',
        'time__hours': 'Часов',
        'time__minutes': 'Минут',
        'time__seconds': 'Секунд'
    },
    'uz': {
        'YesLabel': "Albatta, boraman",
        'NoLabel': "Afsuski, bora olmayman",
        'brideLabel': "Kuyov tomonidan",
        'groomLabel': "Kelin tomonidan",
        'navbar__logo': 'TAKLIFNOMA',
        'hero_header': 'Kamron va Malika',
        'hero_subheader': 'Sizni nikoh kechasiga taklif qilishmoqda <br /> 21.12.2023',
        'invit_header': 'Hurmatli mehmonlar!',
        'invit_body': "Sizni biz uchun muhim bo’lgan kun - nikoh kechamizning quvonchini baham ko'rishga taklif qilishdan mamnunmiz! <br /><br /> Ushbu ajoyib kunni biz sizning mexringizni va qo'llab-quvvatlashingizni his etgan holda barchamiz uchun unutilmas qilib o’tkazishni istaymiz.",
        'invitation': 'Sizni taklif qilamiz!',
        'map': 'Qanday yetib borish mumkin?',
        'plan': 'Nikoh tadbiri rejasi',
        'time__left': 'Qolgan vaqt...',
        'calendar__weekday': 'Payshanba',
        'calendar__weekmonth': 'Dekabr',
        'calendar__month': 'Dekabr 2023',
        'program__header': 'KUN <br /> DASTURI:',
        'program__photo': 'FOTO-<br />SESSIYA',
        'program__event': 'ASOSIY TADBIR',
        'program__cake': 'TORT<br />KESISH',
        'location__header': 'Manzil',
        'location__subheader': 'RESTORAN “GRAND HALL”',
        'location__location': 'Toshkent, Yunusobod tumani, Yunusobod massivi, 13-sonli mahalla, 15A',
        'location__yandex': "Yandex xaritaga o'tish",
        'dress__header': 'Dress kod',
        'dress__subheader': "Kechamizning rang palitrasini qo'llab-quvvatlasangiz, Sizdan minnatdor bo'lamiz.",
        'dress__quest': "So'rovnoma",
        'dress__body': "Sizning tashrifingiz biz uchun juda muhim va biz bu lahzani Siz bilan baham ko'rishdan mamnun  bo'lamiz.",
        'form__header': 'Siz uchun tayyorlagan bir nechta savollarimizga javob berishingizni so’raymiz.',
        'form__form-header': 'Kim tomondan mehmonsiz?*',
        'bride': 'Kelin tomonidan',
        'groom': 'Kuyov tomonidan',
        'form__form-header-attendance': 'Nikoh kechamizga kela olasizmi?*',
        'yes': 'Albatta, boraman',
        'no': 'Afsuski, bora olmayman',
        'form__subheader': 'Agar istasangiz, bu erda bizga bildirmoqchi bo’lgan tilaktaringizni yozib qoldirishingiz mumkin.',
        'form__submit': 'Yuborish',
        'time__header': 'USHBU MUHIM KUNGACHA QOLDI...',
        'time__days': 'Kun',
        'time__hours': 'Soat',
        'time__minutes': 'Daqiqa',
        'time__seconds': 'Sekund'
    }
};
