const translations = {
    'en': {
        'hero_header': 'Kamron & Malika',
        'hero_subheader': 'are inviting You to their wedding <br /> 21.12.2023',
        'invit_header': 'Dear Guests!',
        'invit_body': 'It is a great pleasure to invite You to share the joy of the special event for us - our wedding! <br /><br /> On this wonderful day, we would like to surround ourselves with your warmth and support and make this day unforgettable for all of us.',
        'invitation': 'We invite you!',
        'map': 'How to go there?',
        'plan': 'Plan of wedding',
        'time__left': 'Time left...',
        'calendar__weekday': 'Thursday',
        'calendar__weekmonth': 'December',
        'calendar__month': 'December 2023',
        'program__header': 'PROGRAM OF <br />THE DAY:',
        'program__photo': 'PHOTO-<br />SHOOTING',
        'program__event': 'MAIN EVENT',
        'program__cake': 'CAKE<br />CUTTING',
        'location__header': 'LOCATION',
        'location__subheader': 'RESTAURANT “GRAND HALL”',
        'location__location': 'Tashkent, Yunusabad district, Yunusabad massif, 13th quarter, 15A',
        'location__yandex': 'YANDEX MAPS...',
        'dress__header': 'DRESS CODE',
        'dress__subheader': 'We will be grateful <br /> if You support the wedding <br /> day color palette.',
        'dress__quest': 'QUESTIONNAIRE',
        'dress__body': 'YOUR PRESENCE IS INCREDIBLY <br /> IMPORTANT TO US, AND WE WILL <br /> BE HAPPY TO SHARE THIS <br /> MOMENT WITH YOU.',
        'form__header': 'Please answer a few questions that we have prepared for You.',
        'form__form-header': 'Whose side are you a guest from?',
        'bride': 'Bride’s',
        'groom': 'Groom’s',
        'form__form-header': 'Will you be able to attend our celebration?',
        'yes': 'Certainly, I will be happy to come',
        'no': 'Unfortunately, I will not be able to attend',
        'form__subheader': 'IF YOU WISH YOU CAN SHARE YOUR WISHES TO US HERE',
        'form__submit': 'SEND',
        'time__header': 'WE ARE WAITING <br /> FOR YOU IN...',
        'time__days': 'Days',
        'time__hours': 'Hours',
        'time__minutes': 'Minutes',
        'time__seconds': 'Seconds'
    },
    'ru': {
        'hero_header': 'Камрон и Малика',
        'hero_subheader': 'приглашают вас на свою свадьбу <br /> 21.12.2023',
        'invit_header': 'Дорогие гости!',
        'invit_body': 'Нам большое удовольствие пригласить вас разделить радость этого особенного события для нас - нашей свадьбы! <br /><br /> В этот замечательный день мы хотели бы окружить себя вашим теплом и поддержкой и сделать этот день незабываемым для нас всех.',
        'invitation': 'Мы приглашаем вас!',
        'map': 'Как туда попасть?',
        'plan': 'План свадьбы',
        'time__left': 'Осталось времени...',
        'calendar__weekday': 'Четверг',
        'calendar__weekmonth': 'Декабрь',
        'calendar__month': 'Декабрь 2023',
        'program__header': 'ПРОГРАММА <br />ДНЯ:',
        'program__photo': 'ФОТОСЕССИЯ',
        'program__event': 'ГЛАВНОЕ СОБЫТИЕ',
        'program__cake': 'НАРЕЗКА ТОРТА',
        'location__header': 'МЕСТО',
        'location__subheader': 'РЕСТОРАН "ГРАНД ХОЛЛ"',
        'location__location': 'Ташкент, Юнусабадский район, Юнусабадский массив, 13-й квартал, 15А',
        'location__yandex': 'КАРТЫ ЯНДЕКС...',
        'dress__header': 'ДРЕСС-КОД',
        'dress__subheader': 'Мы будем благодарны, если вы поддержите цветовую палитру свадебного дня.',
        'dress__quest': 'АНКЕТА',
        'dress__body': 'ВАШЕ ПРИСУТСТВИЕ НЕИЗМЕРИМО ВАЖНО ДЛЯ НАС, И МЫ БУДЕМ РАДЫ ПОДЕЛИТЬСЯ ЭТИМ МОМЕНТОМ С ВАМИ.',
        'form__header': 'Ответьте, пожалуйста, на несколько вопросов, которые мы для вас подготовили.',
        'form__form-header': 'Со стороны кого вы гость?',
        'bride': 'Невесты',
        'groom': 'Жениха',
        'form__form-header': 'Сможете ли вы принять участие в нашем торжестве?',
        'yes': 'Конечно, буду рад(а) прийти',
        'no': 'К сожалению, не смогу присутствовать',
        'form__subheader': 'ЕСЛИ ХОТИТЕ, МОЖЕТЕ ПОДЕЛИТЬСЯ С НАМИ СВОИМИ ПОЖЕЛАНИЯМИ ЗДЕСЬ',
        'form__submit': 'ОТПРАВИТЬ',
        'time__header': 'МЫ ЖДЕМ <br /> ВАС В...',
        'time__days': 'Дни',
        'time__hours': 'Часы',
        'time__minutes': 'Минуты',
        'time__seconds': 'Секунды'
    },
    'uz': {
        'hero_header': 'Kamron va Malika',
        'hero_subheader': 'sizni 21.12.2023 sanʼatlariga taklif qilmoqda',
        'invit_header': 'Hurmatli Mehmonlar!',
        'invit_body': 'Sizni bizning ayolligimiz bayramini ulashishga taklif qilish biz uchun katta mamnuniyat hissi. <br /><br /> Ushbu ajoyib kunda, biz oʻzimizni, qiziqishmizni va qoʻllaringizni bilan uzluksiz qilmoqchimiz, va bu kuni biz uchun unutulmaz qilmoqchimiz.',
        'invitation': 'Sizni taklif qilamiz!',
        'map': 'Qanday yetib borish mumkin?',
        'plan': 'Nikoh tadbiri rejasi',
        'time__left': 'Qolgan vaqt...',
        'calendar__weekday': 'Payshanba',
        'calendar__weekmonth': 'Dekabr',
        'calendar__month': 'Dekabr 2023',
        'program__header': 'KUNNING <br /> DASTURI:',
        'program__photo': 'FOTO-<br />SESSIYA',
        'program__event': 'ASOSIY TADBIR',
        'program__cake': 'TORT<br />KESISH',
        'location__header': 'MANZIL',
        'location__subheader': 'RESTORAN “GRAND HALL”',
        'location__location': 'Toshkent, Yunusobod tumani, Yunusobod massivi, 13-sonli mahalla, 15A',
        'location__yandex': 'YANDEX XARITASI...',
        'dress__header': 'LIBOS KODI',
        'dress__subheader': 'Biz toʻy rang palitrasini qoʻllab-quvvatlasangiz, bizga minnatdor boʻlasiz.',
        'dress__quest': 'SOʻROVNAME',
        'dress__body': 'SIZNING MAVJUDLIGINGIZ BIZ UCHUN AQRIBTIRISHIY MEVAQIT, VA BIZ UCHUN BU MOMENTNI SIZ BILAN BIRGA BOʻLISHI BIZNI XURMATLANTIRADI.',
        'form__header': 'Iltimos, siz uchun tayyorlagan qandaydir savollarga javob bering.',
        'form__form-header': 'Siz qaysi tomondan mehmon boʻlishingizni istaysiz?',
        'bride': 'Qiz bola',
        'groom': 'Oʻgʻil bola',
        'form__form-header': 'Siz bizning bayramimizda ishtirok etishingiz mumkin boʻladi mi?',
        'yes': 'Birgamizga kelishdan mamnun boʻlaman',
        'no': 'Afsuski, ishtirok etishim mumkin emas',
        'form__subheader': 'ISTAGAN HOLDA, BIZGA BURADA SOʻZLARINGIZNI QOʻYISHINGIZ MUMKIN',
        'form__submit': 'YUBORISH',
        'time__header': 'BIZ SIZNI <br /> KUTAMIZDA...',
        'time__days': 'Kunlar',
        'time__hours': 'Soatlar',
        'time__minutes': 'Daqiqalar',
        'time__seconds': 'Sekundalar'
    }
};
